apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "5.0.3-v1"
  labels:
    app: kubedb
spec:
  version: "5.0.3"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:5.0.3-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis_exporter:v0.21.1"
  podSecurityPolicies:
    databasePolicyName: redis-db
