apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.0-v1"
  labels:
    app: kubedb
spec:
  version: "4.0.5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.0-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.0-v1"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot
